/**
 * Every word the Add address dialog and its steps show (SCN-021, SCN-061…065), in one place so a
 * locale replaces this module and nothing else. Sentences that carry a value are functions. The
 * registry rows are in docs/brand/strings.md ("Add address (0.12)"). Plain module: tests load it.
 *
 * What the server says (a domain's state, a name's check, a step's detail) arrives in its own words
 * from workers/lib/address-ops.ts and shared/address-name.ts, which are the strings' other home.
 */
export const ADD_ADDRESS_TEXT = {
  title: "Add an address",
  titleAdding: (email: string) => `Adding ${email}`,
  titleAddingSeveral: (domain: string) => `Adding addresses on ${domain}`,
  noDomain: "No domain receives mail here yet.",
  chooseOnDomains: "Choose one on Domains",
  noDomainAfter: " first.",
  modeGroup: "How many",
  modeOne: "One address",
  modeSeveral: "Several",

  addressLabel: "Address",
  addressPlaceholder: "support",
  domainLabel: "Domain",
  chooseDomain: "Choose a domain",
  domainsList: "Domains",
  noDomainMatches: (query: string) => `No domain matches “${query}”.`,
  domainReading: (domain: string) => `Reading ${domain} in Cloudflare…`,
  domainSays: (domain: string, label: string) => `${domain}: ${label.toLowerCase()}.`,
  catchAllKeeps: (mailbox: string) => ` Its catch-all, ${mailbox}, keeps mail for addresses that do not exist.`,
  openToFix: (domain: string) => `Open ${domain} to fix it`,
  receiveFirst: (domain: string) => `${domain} does not receive mail here yet. Create first receives its mail here.`,
  openExisting: (email: string) => `Open ${email}`,
  recentMissing: (domain: string) => `Mail arrived recently for addresses on ${domain} that do not exist:`,

  namesLabel: "Names before @",
  namesPlaceholder: "support\nsales\nhello",
  namesHint: "One per line, or separated by commas or spaces; up to 50.",
  namesList: "Each address",
  nameFree: "Free",
  namesCount: (can: number, all: number) => `${can} of ${all} can be created.`,

  displayName: "Display name",
  displayNamePlaceholder: "Support",
  displayNamePlaceholderSeveral: "Each address's own (Support, Sales…)",
  displayNameHint: "The name your mail and an agent's answers are sent with.",
  whoAnswers: "Who answers",
  policyDraft: "Drafts every answer for you",
  policyAnyAnswer: "any grounded answer",
  policyAuto: (intents: string, limit: number) => `Sends ${intents} · up to ${limit} a day per address`,
  answerOff: "Off — I read it myself",
  answerOffHint: "New mail stays for you; an agent can be chosen later.",
  signatureToggle: (who: string) => `Add a signature to mail sent from ${who}`,
  signatureTheseAddresses: "these addresses",
  signature: "Signature",
  signaturePlaceholder: "Alex Morgan\nSupport, Acme",
  signaturePreview: "Signature preview",
  preview: "Preview",
  previewFrom: (name: string, email: string) => `From: ${name} <${email}>`,
  previewGreeting: "Hello,",
  previewEmpty: "Type a signature to see it here.",

  copyLabel: "Forward a copy to",
  noCopy: "No copy",
  copyNoToken: "Copies are forwarded by Cloudflare: connect it on Domains to choose one.",
  copyLoading: "Loading forwarding destinations…",
  copyFailed: (why: string) => `Forwarding destinations could not load: ${why}`,
  copyConfirmedOnly: "The mail itself always stays here; only confirmed destinations are listed.",
  copyNone: "No confirmed forwarding destination in this domain's Cloudflare account yet.",
  addDestination: "Add a forwarding destination",

  ruleSummary: (state: "made" | "off" | "cannot") =>
    `Cloudflare rule: ${state === "made" ? "made with the address" : state === "off" ? "not made" : "cannot be made here"}`,
  ruleToggle: "Make the Cloudflare rule that sends its mail here",
  ruleCan: "A Cloudflare rule that sends the address's mail here is made with it.",
  ruleCannot: "No rule can be made: this server has no Cloudflare token that sees this domain.",
  ruleWithout: " Without a rule, mail reaches the address only if the domain's catch-all already sends it here.",
  testToggle: "Send a test message once it is created, and watch it arrive",

  cancel: "Cancel",
  create: (email: string) => `Create ${email}`,
  createOne: "Create address",
  createSeveral: (n: number) => (n ? `Create ${n} address${n === 1 ? "" : "es"}` : "Create addresses"),

  // The address field
  nameHint: "Letters a–z, digits, dots, dashes, underscores or plus; a letter or digit at each end.",
  checking: "Checking…",
  checkFailed: "It could not be checked right now; the server checks it again when you create it.",
  isFree: (email: string) => `${email} is free.`,

  // The domain states
  stateReceiving: "Receiving here",
  stateCanReceive: "Can receive here",
  stateNeedsFix: "Needs fixing",
  stateNotVisible: "Token cannot see it",
  stateUnknown: "Routing unknown",
  stateUnavailable: "Not available",

  // The steps
  receiving: (domain: string) => `Receiving ${domain}`,
  creating: "Creating…",
  stepsFor: (email: string) => `What was done for ${email}`,
  replaceContinue: "Replace and continue",
  createdCount: (created: number, all: number, domain: string) => `${created} of ${all} address${all === 1 ? "" : "es"} created on ${domain}.`,
  createdToast: (created: number, all: number, domain: string) => `${created} of ${all} addresses were created on ${domain}.`,
  tryAgain: "Change and try again",
  addAnother: "Add another",
  doneOpen: (email: string) => `Done — open ${email}`,
  close: "Close",
  sendTest: "Send a test message",
  sendAgain: "Send again",
  checkRouting: "Check routing",
  working: "Working…",
  notCreated: "It could not be created.",
  nothingCreated: " Nothing was created.",
  creatingRest: "Creating the rest…",
  // When the server's answer did not arrive, what exists is read again (never "Nothing was created").
  lostExists: (email: string) => `${email} exists now (read again: the server's answer did not arrive).`,
  lostMissing: (email: string, why: string) => `${email} does not exist. ${why} If it does not appear in the address list in a moment, create it again.`,
  lostUnknown: (why: string) => `${why} What was created could not be read: the address list shows which addresses exist.`,
  ruleUnread: "Its rule could not be read. Fix it checks the rule and makes it if it is missing.",

  mark: { done: "Done", already: "Already so", skipped: "Skipped", failed: "Not done", not_receiving: "Not receiving yet", waiting: "Waiting", running: "Working…", not_asked: "Not asked" },
  details: "Details",
  chip: (step: string, mark: string) => `${step}: ${mark.toLowerCase()}`,
  titleAdded: (email: string) => `Added ${email}`,
  titleAddedSeveral: (domain: string) => `Added on ${domain}`,
  stepAddress: "Create the address",
  stepRule: "Send its mail here",
  stepTest: "Send a test message",
  stepReceive: (domain: string) => `Receive mail for ${domain} here`,
  receiveRunning: "Turning on Email Routing and bringing in its addresses…",
  receiveMx: (domain: string, mx: string) => `Another provider handles mail for ${domain} today (MX ${mx}). Receiving here replaces those records, so mail stops reaching that provider.`,
  receiveFailed: (label: string, detail: string) => `${label}: ${detail} Nothing was created; creating again continues from there.`,
  receiveError: (error: string) => `${error} Nothing was created.`,
  receiveDone: (domain: string, now: boolean) => `${domain} receives mail here${now ? " now" : ""}.`,
  testOff: "Send one now to see mail arrive.",
  testSending: "Sending it from the address to itself…",
  testCouldNot: "It could not be sent.",
  testSent: "Sent; waiting for it to arrive.",
  testArrived: (time: string, folder: string | null) => `Arrived at ${time}${folder ? ` in ${folder}` : ""}: mail sent to this address reaches it here.`,
  testWaiting: (detail: string) => `${detail} Checked every 5 seconds.`,

  sentenceNotCreated: (email: string, detail: string) => `${email} was not created. ${detail}`.trim(),
  sentencePartly: (email: string, step: string, fix: string | null) => `${email} was created; ${step.toLowerCase()} did not happen.${fix ? ` ${fix} fixes it.` : ""}`,
  sentenceNotReceiving: (email: string, fix: string | null) => `${email} was created; its mail does not arrive here yet.${fix ? ` ${fix} fixes it.` : ""}`,
  sentenceWaiting: (email: string) => `${email} was created. Waiting for the test message…`,
  sentenceReady: (email: string) => `${email} is ready: the test message arrived.`,
  sentenceCreated: (email: string) => `${email} was created.`,

  // The entry points (AddressesSection, DomainsSection)
  addOnDomain: (domain: string) => `Add an address on ${domain}`,
  addFirst: "Add the first address",
  addFirstOnDomain: (domain: string) => `Add the first address on ${domain}`,
  domainEmpty: (domain: string, catchAll: string | null) => `No address on ${domain} yet: mail to it ${catchAll ? `is kept in ${catchAll}` : "is refused, and the sender is told"}.`,
  listEmptyNoDomains: "No address yet. An address lives on one of your domains: connect Cloudflare on Domains so they can be chosen.",
  listEmptyOn: (domains: string[]) => `No address yet on ${domains.length > 3 ? `${domains.slice(0, 3).join(", ")} and ${domains.length - 3} more` : domains.join(", ")}.`,
  listEmptyNoneServed: "No domain receives mail here yet. Adding an address on one of your domains receives its mail here first.",
  addDisabled: "Connect Cloudflare, or receive a domain's mail here first (Domains)",

  // The address's panel (AddressesSection)
  panelConnect: "Connect Cloudflare to make and check its rule:",
  panelConnectLink: "Connect Cloudflare",
  panelElsewhere: "A rule sending it elsewhere is never overwritten from here: change it in Cloudflare, or use Bring them here on",
  panelElsewhereAfter: ", which keeps a copy.",
  panelFix: "Fix it",
  panelFixTitle: "Makes or switches on the Cloudflare rule that sends its mail here",
  panelSendTest: "Send a test message",
  panelTestSending: "Sending a test…",
  panelTestRefused: (subject: string) => `The provider refused the test message “${subject}”.`,
  panelTestSent: (subject: string) => `Test message “${subject}” sent; its arrival is watched below.`,
  panelLastTest: "The last test message",
  panelTestOf: (when: string) => `Test of ${when}.`,
} as const;
