/**
 * Writes the tool reference of docs/agents/mcp.md from workers/mcp/tools.ts (AP-8): the part
 * between the `tools:start` and `tools:end` markers. `--check` changes nothing and exits 1 when
 * the document is stale. `npm run mcp:docs` writes; tests/mcp-docs.test.ts checks.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { NOT_TOOLS, TOOLS } from "../workers/mcp/tools";
import type { ToolDef } from "../workers/mcp/protocol";

export const DOC_PATH = fileURLToPath(new URL("../docs/agents/mcp.md", import.meta.url));
const START = "<!-- tools:start (generated by npm run mcp:docs; do not edit by hand) -->";
const END = "<!-- tools:end -->";

type Any = z.ZodTypeAny;
function typeOf(schema: Any): string {
  const def = schema._def as { typeName: string; [k: string]: unknown };
  switch (def.typeName) {
    case "ZodOptional": case "ZodNullable": case "ZodDefault": return typeOf(def.innerType as Any) + (def.typeName === "ZodNullable" ? " or null" : "");
    case "ZodEffects": return typeOf(def.schema as Any);
    case "ZodString": return "string";
    case "ZodNumber": return (def.checks as { kind: string }[] | undefined)?.some((c) => c.kind === "int") ? "integer" : "number";
    case "ZodBoolean": return "boolean";
    case "ZodEnum": return (def.values as string[]).map((v) => `"${v}"`).join(" \\| ");
    case "ZodLiteral": return JSON.stringify(def.value);
    case "ZodArray": return `${typeOf(def.type as Any)}[]`;
    case "ZodUnion": return (def.options as Any[]).map(typeOf).join(" or ");
    case "ZodObject": return "object";
    case "ZodRecord": return "object";
    default: return "value";
  }
}
function defaultOf(schema: Any): unknown {
  let s: Any = schema;
  while (s) {
    const def = s._def as { typeName: string; innerType?: Any; defaultValue?: () => unknown };
    if (def.typeName === "ZodDefault") return def.defaultValue!();
    if (def.typeName === "ZodOptional" || def.typeName === "ZodNullable") { s = def.innerType!; continue; }
    return undefined;
  }
  return undefined;
}
const cell = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\|/g, "\\|").replace(/\n/g, " ");

function inputs(tool: ToolDef): string {
  const entries = Object.entries(tool.input as Record<string, Any>);
  if (tool.confirm) entries.push(["confirm", z.string().optional().describe("The code from the first call (two-step)")]);
  if (!entries.length) return "none";
  return entries.map(([name, schema]) => {
    const required = !schema.isOptional();
    const dflt = defaultOf(schema);
    const bits = [`\`${name}\``, typeOf(schema), required ? "required" : dflt !== undefined ? `default ${JSON.stringify(dflt)}` : "optional"];
    return `${bits.join(" · ")}${schema.description ? ` — ${schema.description}` : ""}`;
  }).map((l) => `- ${cell(l)}`).join("<br>");
}

const LEVEL_TITLE = { read: "Reading (level `read` and up)", mail: "Mail (level `mail` and up)", admin: "Administration (level `admin`)" } as const;

export function renderTools(): string {
  const out: string[] = [START, ""];
  out.push(`${TOOLS.length} tools. **Sends** — hidden from a *Drafts only* key and counted against its daily sends. **Two steps** — the first call returns a summary and a code (see [Two steps](#two-steps)). **Changes nothing** — not journalled.`, "");
  for (const level of ["read", "mail", "admin"] as const) {
    const tools = TOOLS.filter((t) => t.level === level);
    out.push(`### ${LEVEL_TITLE[level]}`, "", "| Tool | What it does | Inputs | Kind | Routes |", "|---|---|---|---|---|");
    for (const t of tools) {
      const kind = [t.readOnly ? "changes nothing" : "", t.sends ? "**sends**" : "", t.confirm ? "**two steps**" : ""].filter(Boolean).join(", ") || "changes";
      out.push(`| \`${t.name}\` | ${cell(t.description)} | ${inputs(t)} | ${kind} | ${t.routes.map((r) => `\`${r}\``).join("<br>")} |`);
    }
    out.push("");
  }
  out.push("### Routes no tool calls", "", "| Route | Why |", "|---|---|");
  for (const [route, why] of Object.entries(NOT_TOOLS)) out.push(`| \`${route}\` | ${cell(why)} |`);
  out.push("", END);
  return out.join("\n");
}

export function withTools(doc: string): string {
  const start = doc.indexOf(START.slice(0, 20));
  const end = doc.indexOf(END);
  if (start < 0 || end < 0) throw new Error(`${DOC_PATH} has no tools:start / tools:end markers`);
  return doc.slice(0, start) + renderTools() + doc.slice(end + END.length);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const current = readFileSync(DOC_PATH, "utf8");
  const next = withTools(current);
  if (process.argv.includes("--check")) {
    if (next !== current) { console.error("docs/agents/mcp.md is stale: run npm run mcp:docs"); process.exit(1); }
    console.log("docs/agents/mcp.md is current");
  } else if (next !== current) { writeFileSync(DOC_PATH, next); console.log(`docs/agents/mcp.md: ${TOOLS.length} tools written`); }
  else console.log("docs/agents/mcp.md already current");
}
