// Every user-facing string of the triage keys, Discarded and the Undo toast in one place, so the
// localization that follows (Russian: Discarded = «Выброшенные») translates one table, not the
// components. Plain module: the tests and the components read it. Wording: docs/brand/strings.md.

export const TRIAGE_TEXT = {
  folder: "Discarded",
  emptyTitle: "Nothing discarded",
  emptyBody: "Discard a message with ⌘⌫ (Ctrl+Backspace) and it waits here 30 days; mail like it comes here on its own after that.",
  banner: "Discarded mail is deleted after 30 days (in Gmail, IMAP and Outlook accounts it moves to their Trash). Nothing here reaches an agent, a rule or a category.",
  bannerLink: "Discard rules",
  whyDiscarded: "Why discarded:",
  discardButton: "Discard message",
  discardTitle: (key: string) => `Discard: out of the inbox, and mail like it from now on (${key})`,
  archiveTitle: (key: string) => `Archive and mark read (${key})`,
  notDiscarded: "Not discarded",
  notDiscardedTitle: "Not discarded: back to the inbox",
  backInInbox: "Back in the inbox.",
  stillDiscarding: (labels: string) => `Back in the inbox. Future mail from ${labels} still goes to Discarded.`,
  stopDiscarding: "Stop discarding mail like this",
  ruleRemoved: (label?: string) => `Mail${label ? ` from ${label}` : " like this"} will not be discarded on its own. Discarded mail stays where it is.`,
  ruleNotRemoved: (error: string) => `The rule could not be removed: ${error} Remove it in Settings → Discard rules.`,
  selected: (n: number) => `${n} selected`,
  selectedTitle: (n: number) => `${n} messages selected`,
  selectedBody: "Act on all of them at once, or press Esc to clear the selection.",
  archive: "Archive",
  discard: "Discard",
  clearSelection: "Clear selection",
  shortcutsNav: "Keyboard shortcuts",
  undo: "Undo",
  undoing: "Undoing…",
  undone: (n: number) => (n === 1 ? "Undone." : `Undone: ${n} messages are back.`),
  undoFailed: (restored: number, failed: number, first: string) => `${restored ? `${restored} came back; ` : ""}${failed} could not: ${first}`,
  dont: "Don't",
  dismiss: "Dismiss",
  // What an action did (triage-actions.ts).
  archived: "archived",
  discarded: "discarded",
  done: (verb: string, n: number) => (n === 1 ? verb[0]!.toUpperCase() + verb.slice(1) : `${n} messages ${verb}`),
  someFailed: (n: number, first: string) => `; ${n} could not be: ${first}`,
  futureMail: (who: string) => `Future mail from ${who} will go to Discarded.`,
  andOthers: (first: string, more: number) => `${first} and ${more} others`,
  and: (a: string, b: string) => `${a} and ${b}`,
  notDiscardedAny: "It could not be discarded",
  notRestored: "It could not be brought back",
  // Why an action cannot be done here (triage-actions.ts canAct).
  alreadyArchived: "It is already archived.",
  archiveInboxOnly: "Archive works on mail in the inbox; use the buttons above the message here.",
  noArchiveFolder: "This account has no Archive folder; discard or trash it instead.",
  alreadyDiscarded: "It is already discarded.",
  sentNotDiscardable: "Mail in Sent is yours: it cannot be discarded.",
} as const;
